
__author__ = ["POD/LCA Team"]
__copyright__ = "University of Washington"
__license__ = "MIT License"
__email__ = "mhtaba@uw.edu"
__version__ = "0.1.0"

from time import time

from .logistics_link import LogisticLink
from ...units import KILOMETER
from ...units import MILE
from ...utilities import log


class DomesticLink(LogisticLink):
    """ A link of domestic US transportation.

    Attributes
    ----------
    transport_scenario : str
        A discriptor of the tranportation scenario.
    """

    def __init__(self):
        super().__init__()
        self.transport_scenario = None
        self._cache_travel_dist = None
        self._last_params = None

    # ================================
    # Setters
    # ================================  
    def set_transport_scenario(self, transport_scenario:(str)):
        """ Set the transport scenario of the transportation link.

        Parameters
        ----------
        transport_scenario : str
            Transport scenario of the transportation link (e.g., "North_america", "Global").
        """
        if transport_scenario is None:
            self.transport_scenario = None
        elif isinstance(transport_scenario, str):
            if transport_scenario in ["National", "Regional", "Regional_c", "Local"]:
                self.transport_scenario = transport_scenario
            else:
                raise ValueError("Transportation scenario not recognized")
        else:
            raise ValueError("Transport scenario must be a string.")

        self._invalidate_cache()
        return self
    
    def set_material(self, material):
        """ Set the quantity of the transportation link.

        Parameters
        ----------
        material : Master Obj.
            Material name of the transportation link.
        """
        self = super().set_material(material)
        self._invalidate_cache()
        return self
    
    def set_shipping_destination(self, shipping_dest):
        """ Set the shipping destination of the project.

        Parameters
        ----------
        shipping_dest : Location Obj.
            Name of the shipping destination location.
        """
        self = super().set_shipping_destination(shipping_dest)
        self._invalidate_cache()
        return self
        
    def set_shipping_origin(self, shipping_org):
        """ Set the shipping origin of the project.

        Parameters
        ----------
        shipping_org : Location Obj.
            Name of the shipping origin location.
        """
        self = super().set_shipping_origin(shipping_org)
        self._invalidate_cache()
        return self

    def set_mode(self, mode=None, fuel_type=None , efficiency=None):
        """ Set the transportation mode of the transportation link.

        Parameters
        ----------
        mode : str or TransportMode Obj
            transportation mode of the transportation link.
        fuel_type : str
            type of fuel used in the transportation mode (default is "Regular").
        efficiency : str
            efficiency of the transportation mode "low, medium, high" (default is "medium").
        """
        self = super().set_mode(mode, fuel_type, efficiency)
        self._invalidate_cache()
        return self
    
    def set_travel_dist(self, travel_dist=None, travel_dist_unit=None, return_trip_factor=None):
        """ Set the travel distance of the transportation link.

        Parameters
        ----------
        travel_dist : None
            For DomesticLink objects travel distance are autogenerated from CFS data.
        travel_dist_unit : Unit Obj
            Unit of the travel distance.
        return_trip_factor : float
            Return trip factor of the transportation link (default is None).
        """
        self.travel_dist_unit = KILOMETER if travel_dist_unit is None else travel_dist_unit
        self._invalidate_cache()
        return self

    # ================================
    # Getters
    # ================================  
    def get_transport_scenario(self):
        """ Retrieve the transport scenario of the transportation link.

        Returns
        -------
        str
            The transport scenario of the transportation link.
        """
        return self.transport_scenario
    
    def get_travel_dist(self):
        """ Set the travel distance of the transportation link.

        Returns
        -------
        float or str
            travel distance of the transportation link.
        """
        current_params = (self.get_material(), 
                          self.get_shipping_destination(), 
                          self.get_shipping_origin(), 
                          self.get_mode().get_name(),
                          self.get_mode().get_efficiency(),
                          self.get_transport_scenario(), 
                          self.get_dist_unit())
        
        if self._last_params == current_params and self._cache_travel_dist is not None:
            log("Returning cached result.", "Info")
            return self._cache_travel_dist
        else:
            transport_scenario = self.get_transport_scenario()
            if transport_scenario in ["Local", "Regional", "Regional_c", "National", None]:
                try:
                    travel_dist = self.get_distance_from_cfs(transport_scenario)
                except ValueError as e:
                    if str(e) == "Transportation mode not in CFS dataset":
                        # TODO: verify this logic in view of the resulting inconsistencies
                        log(f"Transportation mode not found in CFS dataset. Using default mode 'Truck'.", "Warn")
                        self.set_mode('Truck', self.get_mode().get_fuel_type(), self.get_mode().get_efficiency())

                        travel_dist = self.get_distance_from_cfs(transport_scenario)
            else:
                raise ValueError("Transport scenario not recognized.")

            self._cache_travel_dist = travel_dist
            self._last_params = current_params

            return travel_dist

    def get_return_trip_factor(self):   
        """ Retrieve the return trip factor of the transportation link.

        Returns
        -------
        float
            The return trip factor of the transportation link.
        """
        dist = self.get_travel_dist()
        convertion_factor = self.get_dist_unit().get_conversion_factor(MILE)

        return 1.5 if dist * convertion_factor < 500 and self.get_mode().get_name() == "Truck" else 1.0
        
    # ================================
    # CFS Methods
    # ================================
    def get_distance_from_cfs(self, transport_scenario):
        """ Get the average distance from the CFS dataset based on the scenario.

        Parameters
        ----------
        scenario : str
            The scenario to filter the distances by.

        Returns
        -------
        float
            The distance estimate for the specified scenario.
        """
        dataset = self.get_project().get_dataset()

        conversion_factor = self.get_dist_unit().get_conversion_factor(KILOMETER)
        sctg_code = dataset.get_sctg_code(self.get_material().get_name())
        cfs_filtered = dataset.filter_datasets(sctg_code, self.get_shipping_destination(), self.get_shipping_origin(), self.get_mode())
        travel_dist = dataset.get_distance_estimate(cfs_filtered, transport_scenario) * conversion_factor

        return travel_dist
    
    # ================================
    # Cache Method
    # ================================
    def _invalidate_cache(self):
        self._cache_travel_dist = None
        self._last_params = None


if __name__ == '__main__':
    pass
