
__author__ = ["POD/LCA Team"]
__copyright__ = "University of Washington"
__license__ = "MIT License"
__email__ = "mhtaba@uw.edu"
__version__ = "0.1.0"

from geopy.distance import geodesic

from . import CFSDataset
from . import LogisticLink
from . import TransportMode
from ..location import Location
from ...units import KILOMETER
from ...utilities import config
from ...utilities import DataImporter
from ...utilities import log


class ForeignLink(LogisticLink):
    """ A link of Global transportation.
    
    Attributes
    ----------
    transport_scenario : str
        A discriptor of the tranportation scenario.
    """

    def __init__(self):
        super().__init__()
        self.transport_scenario = None

    # ================================
    # Constructors
    # ================================
    @classmethod
    def in_project(cls, good, project, name=None):
        """ Create a new transportation link in the project.

        Parameters
        ----------
        good : Master obj.
            Product being transported.
        project : Project obj.
            The project to which the transportation link belongs.
        name : str, optional
            Name of the transportation link (default is None).

        Returns
        -------
        LogisticLink obj.
            Transportation link created in the project.
        """
        link = super().in_project(good, project, name)

        link_domestic_leg = LogisticLink.in_project(good, project, name + '_domestic')
        link.set_next(link_domestic_leg)

        return link
    
    # ================================
    # Setters
    # ================================
    def set_transport_scenario(self, transport_scenario:(str)):
        """ Set the transport scenario of the transportation link.

        Parameters
        ----------
        transport_scenario : str
            Transport scenario of the transportation link (e.g., "North_america", "Global").
        """
        if transport_scenario is None:
            self.transport_scenario = None # TODO set the default transport scenario
        elif isinstance(transport_scenario, str):
            if transport_scenario in ["Global", "North_america"]:
                self.transport_scenario = transport_scenario
            else:
                raise ValueError("Transportation scenario not recognized")
        else:
            raise ValueError("Transport scenario must be a string.")

        return self
    
    def set_travel_dist(self, travel_dist=None, dist_unit=None, return_trip_factor=None):
        """ Set the travel distance of the transportation link.

        Parameters
        ----------
        travel_dist : None
            For ForeignLink objects travel distance are autogenerated using a dataset.
        dist_unit : Unit Obj
            Unit of the travel distance.
        return_trip_factor : float
            Return trip factor of the transportation link (default is None).
        """
        self.dist_unit = KILOMETER if dist_unit is None else dist_unit
        self.return_trip_factor = return_trip_factor

        return self
    
    def set_mode(self, mode, fuel_type, efficiency):
        """ Set the transportation mode of the transportation link.

        Parameters
        ----------
        mode : str, dict, or TransportMode Obj
            Transportation mode of the transportation link.
            Can also be provided as a dictionary keyed by 'domestic' and 'foreign'.
        fuel_type : str or dict
            Type of fuel used in the transportation mode (default is "Regular").
            Can also be provided as a dictionary keyed by 'domestic' and 'foreign'.
        efficiency : str or dict
            Efficiency of the transportation mode "low, medium, high" (default is "medium").
            Can also be provided as a dictionary keyed by 'domestic' and 'foreign'.
        """
        if isinstance(mode, TransportMode):
            self.mode = mode
            self.get_next().set_mode(domestic_mode)
        
        elif isinstance(mode, str) or mode is None:
            fuel_type = "Regular" if fuel_type is None else fuel_type
            mode_efficiency = "Median" if efficiency is None else efficiency
            mode_name = "Truck" if mode is None else mode

            mode_obj = TransportMode.new(mode_name, mode_efficiency, fuel_type)

            self.mode = mode_obj
            self.get_next().set_mode(mode_obj)

        elif isinstance(mode, dict):
            domestic_mode_name = mode['domestic'] if 'domestic' in mode and isinstance(mode['domestic'], str) else 'Truck'
            foreign_mode_name = mode['foreign'] if 'foreign' in mode and isinstance(mode['foreign'], str) else 'Ocean'
            
            if isinstance(efficiency, dict):
                domestic_mode_efficiency = efficiency['domestic'] if 'domestic' in efficiency and isinstance(efficiency['domestic'], str) else 'Median'
                foreign_mode_effciency = efficiency['foreign'] if 'foreign' in efficiency and isinstance(efficiency['foreign'], str) else 'Median'
            elif isinstance(efficiency, (str, None)):
                foreign_mode_effciency = efficiency if isinstance(efficiency, str) else 'Median'
                domestic_mode_efficiency = efficiency if isinstance(efficiency, str) else 'Median'
            else:
                raise ValueError("Transport efficiency not recognized.")
            
            if isinstance(fuel_type, dict):
                domestic_mode_fuel_type = fuel_type['domestic'] if 'domestic' in fuel_type and isinstance(fuel_type['domestic'], str) else 'Regular'
                foreign_mode_fuel_type = fuel_type['foreign'] if 'foreign' in fuel_type and isinstance(fuel_type['foreign'], str) else 'Regular'
            elif isinstance(fuel_type, (str, None)):
                foreign_mode_fuel_type = fuel_type if isinstance(fuel_type, str) else 'Regular'
                domestic_mode_fuel_type = fuel_type if isinstance(fuel_type, str) else 'Regular'
            else:
                raise ValueError("Transport fuel type not recognized.")
            
            self.mode = TransportMode.new(foreign_mode_name, foreign_mode_effciency, foreign_mode_fuel_type)
    
            domestic_mode =TransportMode.new(domestic_mode_name, domestic_mode_efficiency, domestic_mode_fuel_type)
            self.get_next().set_mode(domestic_mode)

        else:
            raise TypeError(f"Invalid type for mode: {type(mode)}. Must be TransportMode Object, str or dict.")

        self.mode.set_parent(self)
        self.mode.set_inventory_records()
        
        return self
    
    def get_shipping_origin(self):
        """ Set the shipping origin of the project.

        Returns
        ----------
        Location Obj
            Name of the shipping origin location.
        """
        if self.shipping_org is None:
            if self.get_transport_scenario() in ["North_america", "Global"]: # TODO: verify this
                Faf_city_representation = DataImporter.json_to_dict(config['file_paths']['location']['FAF_CITY_REPRESENTATION'])
                faf  = DataImporter.csv_to_pandas(config['file_paths']['transportation']['FAF_DATA_PATH'])
                faf = faf[faf["fr_orig"].isin([801, 802])] if self.get_transport_scenario() == "North_america" else faf[faf["fr_orig"].isin([801, 802]) == False]
                faf = faf[faf["fr_orig"] == faf["fr_orig"].mode()[0]]

                self.shipping_org = Location.from_str(Faf_city_representation[str(int(faf["fr_orig"].mode()[0]))])

        return self.shipping_org

    # ================================
    # Getters
    # ================================
    def get_transport_scenario(self):
        """ Retrieve the transport scenario of the transportation link.

        Returns
        -------
        str
            The transport scenario of the transportation link.
        """
        return self.transport_scenario
     
    def get_travel_dist(self):
        """ Get the travel distance of the transportation link.

        Parameters
        ----------
        float
            travel distance of the transportation link.
        """
        transport_scenario = self.get_transport_scenario()

        domestic_dis, foreign_dis = self.get_distance_from_dataset(transport_scenario)
        travel_dist = foreign_dis
        self.get_next().set_travel_dist(domestic_dis, self.get_dist_unit(), None)                       

        return travel_dist

    def get_return_trip_factor(self):   
        """ Retrieve the return trip factor of the transportation link.

        Returns
        -------
        float
            The return trip factor of the transportation link.
        """
        return 1.0
    
    # ================================
    # Dataset Methods
    # ================================
    def get_distance_from_dataset(self, transport_scenario):
        """ Get the average distance from the CFS dataset based on the scenario.

        Parameters
        ----------
        scenario : str
            The scenario to filter the distances by.

        Returns
        -------
        float
            The distance estimate for the specified scenario.
        """
        dataset = self.get_project().get_dataset()

        conversion_factor = self.get_dist_unit().convert_to(KILOMETER)

        datasets_filtered = dataset.filter_datasets(self.get_material(), self.get_shipping_destination(), self.get_shipping_origin(), self.get_next().get_mode(), self.get_mode(), transport_scenario)
        domestic_dis, foreign_dis = dataset.get_travel_dist(datasets_filtered, self.get_shipping_destination(), self.get_shipping_origin(), self.get_mode().get_name())

        return domestic_dis * conversion_factor, foreign_dis * conversion_factor


if __name__ == '__main__':
    pass
