__author__ = ["POD/LCA Team"]
__copyright__ = "University of Washington"
__license__ = "MIT License"
__email__ = "mhtaba@uw.edu"
__version__ = "0.1.0"

from .transport_leg import TransportationLeg
from ...units import KILOMETER
from ...units import MILE
from ...utilities import log


class DomesticLeg(TransportationLeg):
    """A leg of domestic US transportation.

    Attributes
    ----------
    transport_scenario : {'Local', 'Regional', 'National', 'N/A', 'No Scenario'}
        A discriptor of the tranportation scenario. N/A when scenario not applicable (i.e., origin and destination both known).
        'No Scenario' when insufficient data points to get scenarios.
    """

    def __init__(self):
        super().__init__()
        self.transport_scenario = None
        self._cache_travel_dist = None
        self._last_params = None

    # ================================
    # Setters
    # ================================
    def set_transport_scenario(self, transport_scenario: str):
        """Set the transport scenario of the transportation leg.

        Parameters
        ----------
        transport_scenario : {'Local', 'Regional', 'National', 'N/A', 'No Scenario'}
            Transport scenario of the transportation leg.

        Raises
        ------
        ValueError
            Transportation scenario not recognized.
        TypeError
            Transportation scenario is not None or a string.
        """
        if transport_scenario is None:
            self.transport_scenario = "N/A"
        elif isinstance(transport_scenario, str):
            if transport_scenario in ["Local", "Regional", "National", "N/A", "No Scenario"]:
                self.transport_scenario = transport_scenario
            else:
                raise ValueError("Transportation scenario not recognized")
        else:
            raise TypeError("Transport scenario must be a string.")

        self._invalidate_cache()
        return self

    def set_material(self, material):
        """Set the material being transported.

        Parameters
        ----------
        material : ~pod_lca.materials_screening.Product
            Material being transported.
        """
        self = super().set_material(material)
        self._invalidate_cache()
        return self

    def set_shipping_destination(self, shipping_dest):
        """Set the shipping destination of the project.

        Parameters
        ----------
        shipping_dest : ~pod_lca.location.Location
            Shipping destination location.
        """
        self = super().set_shipping_destination(shipping_dest)
        self._invalidate_cache()
        return self

    def set_shipping_origin(self, shipping_org):
        """Set the shipping origin of the project.

        Parameters
        ----------
        shipping_org : ~pod_lca.location.Location
            Shipping origin location.
        """
        self = super().set_shipping_origin(shipping_org)
        self._invalidate_cache()
        return self

    def set_mode(self, mode=None, efficiency=None):
        """Set the transportation mode of the transportation leg.

        Note
        ----
        1. Prefix `'E_'` in the mode_name is used as the identifier of an electricity based transportation mode.
        2. Electric vehicles takes electricity based on origin location.

        Parameters
        ----------
        mode : str or ~pod_lca.transportation.TransportMode
            transportation mode of the transportation leg.
        efficiency : {'High', 'Median', 'Low'}
            efficiency of the transportation mode.
        """
        self = super().set_mode(mode, efficiency)
        self._invalidate_cache()
        return self

    def set_travel_dist(self, travel_dist=None, dist_unit=None, return_trip_factor=None):
        """Set the travel distance of the transportation leg.

        Parameters
        ----------
        travel_dist : None
            For travel distance are autogenerated from CFS data.
        dist_unit : ~pod_lca.units.Unit
            Unit of the travel distance.
        return_trip_factor : float
            Return trip factor of the transportation leg.
        """
        self.dist_unit = KILOMETER if dist_unit is None else dist_unit
        self.travel_dist = travel_dist
        self.return_trip_factor = return_trip_factor

        self._invalidate_cache()
        return self

    # ================================
    # Getters
    # ================================
    def get_transport_scenario(self):
        """Retrieve the transport scenario of the transportation leg.

        Returns
        -------
        str
            The transport scenario of the transportation leg.
        """
        return self.transport_scenario

    def get_travel_dist(self):
        """Set the travel distance of the transportation leg.

        Returns
        -------
        float or str
            travel distance of the transportation leg.

        Raises
        ------
        ValueError
            Transport scenario not recognized.
        """
        current_params = (
            self.get_material(),
            self.get_shipping_destination(),
            self.get_shipping_origin(),
            self.get_mode().get_name(),
            self.get_mode().get_efficiency(),
            self.get_transport_scenario(),
            self.get_dist_unit(),
        )

        if self._last_params == current_params and self._cache_travel_dist is not None:
            log("Returning cached result.", "Info")
            return self._cache_travel_dist
        elif self.travel_dist is not None:
            return self.travel_dist
        else:
            travel_dist = self.get_distance_from_datset()

            self._cache_travel_dist = travel_dist
            self._last_params = current_params

            return travel_dist

    def get_return_trip_factor(self):
        """Retrieve the return trip factor of the transportation leg.

        Returns
        -------
        float
            The return trip factor of the transportation leg.
        """
        dist = self.get_travel_dist()
        convertion_factor = self.get_dist_unit().convert_to(MILE)

        return 1.5 if dist * convertion_factor < 500 and self.get_mode().get_name() == "Truck" else 1.0

    def get_dataset(self):
        """Get the dataset."""
        return self.get_manager().get_dataset()["domestic"]

    # ================================
    # CFS Methods
    # ================================
    def get_distance_from_datset(self):
        """Get the average distance from the CFS dataset based on the scenario.

        Note
        ----
        CFS dataset gives distances in kilometres.

        Parameters
        ----------
        scenario : str
            The scenario to filter the distances by.

        Returns
        -------
        float
            The distance estimate for the specified scenario.
        """
        dataset = self.get_dataset()

        conversion_factor = KILOMETER.convert_to(self.get_dist_unit())
        cfs_filtered = dataset.filter_datasets(
            self.get_material(), self.get_shipping_destination(), self.get_shipping_origin(), self.get_mode()
        )
        bins, _ = dataset.get_data_bins(cfs_filtered, target_bins=3)

        # update scenario
        transport_scenario = self.get_transport_scenario() if self.get_shipping_origin() is None else "N/A"
        if not self.get_transport_scenario() == "N/A":
            if bins == 1:
                transport_scenario = "No Scenario"
        self.set_transport_scenario(transport_scenario)

        travel_dist = dataset.get_distance_estimate(cfs_filtered, transport_scenario) * conversion_factor

        return travel_dist

    # ================================
    # Cache Method
    # ================================
    def _invalidate_cache(self):
        self._cache_travel_dist = None
        self._last_params = None


if __name__ == "__main__":
    pass
