setup:
  electricity:
    DEFAULT_REIGIONAL_RESOLUTION: National
    DEFAULT_COUNTRY: USA
    DEFAULT_COUNTRY_CODE: US
    DEFAULT_YEAR: 2025
    DEFAULT_SCENARIO: MidCase
    DEFAULT_DECLARED_UNIT: MWh
    CAMBIUM_DATA_YEARS: [2025, 2030, 2035, 2040, 2045, 2050]
  utilities:
    LOG_LEVEL: Info


file_paths:
  electricity:
    CAMBIUM_NATIONAL_DATA: data\\electricity_cambium_consumption-national.csv
    CAMBIUM_REGIONAL_DATA: data\\electricity_cambium_consumption-regional.csv
    CAMBIUM_LOCAL_DATA: data\\electricity_cambium_consumption-local.csv
    CAMBIUM_HEADER_MAP: data\\electricity_cambium_technology-headers.json
    CAMBIUM_TECHNOLOGY_MAP: data\\electricity_cambium_technology-map.json
    CAMBIUM_REGIONS_MAP: data\\electricity_cambium_regions-map.json
    ELECTRICITY_IMPACT_NATIONAL_DATA: data\\electricity_netl_national-consumption-impacts-by-technology.csv
    ELECTRICITY_IMPACT_REGIONAL_DATA: data\\electricity_netl_regional-consumption-impacts-by-technology.csv
    ELECTRICITY_TECHNOLOGIES: data\\electricity_netl_electricity-technologies.csv
