setup:
  INVENTORY_ITEMS:
    IMPACT_CATEGORIES:
      GWP: kg CO2 eq # IPCC AR5, 2013, 100-yr, w/o climate carbon feedback
      GWP_fossil: kg CO2 eq
      GWP_biogenic: kg CO2 eq
      GWP_luluc: kg CO2 eq
      AP: kg SO2 eq
      EP: kg N eq
      ODP: kg CFC-11 eq
      POCP: kg O3 eq
      NREF: MJ
    EMISSION_INVENTORIES:
      CO2: kg
      CH4: kg
      CH4 fossil: kg
      N2O: kg
    CARBON_STORAGE:
      Biogenic C: kg C
      Mineral C: kg CO2 # accelerated carbonation uptake
  electricity:
    DEFAULT_REIGIONAL_RESOLUTION: National # Options: National, Regional, Local
    DEFAULT_COUNTRY: USA
    DEFAULT_COUNTRY_CODE: US
    DEFAULT_YEAR: 2025
    DEFAULT_SCENARIO: MidCase
    DEFAULT_DECLARED_UNIT: MWh
    CAMBIUM_DATA_YEARS: [2025, 2030, 2035, 2040, 2045, 2050]
  eol:
    EOL_DEFAULT_KEY: DEFAULT
    WASTE_PROCESS_STAGES:
      Recycle: C3
      Compost: C3
      Incinerate: C4
      Landfill: C4
  impacts:
    IMPACT_SOURCE_DATABASE: 'FLCAC' # Options: 'FLCAC' or 'ecoinvent391'
    PRIMARY_IMPACT_CATEGORY: GWP
    CARBONATION_EFFECTS_IMPACT_CATEGORY: GWP
    ACCELERATED_CARBONATION_INVENTORY: Mineral C
    ACCELERATED_CARBONATION_POTENTIAL_DATABASE_HEADER: Mineral Carbonation Potential
    BIOGENIC_CARBON_STORAGE_INVENTORY: Biogenic C
    BIOGENIC_CARBON_STORAGE_POTENTIAL_DATABASE_HEADER: Stored Biogenic Carbon
  drf:
    IPCC_REPORT_VERSION: AR5
  operational:
    EPLUS_VERSION: '25.1.0' # Version of Energy + used in this release of POD_LCA
    TERRAIN: 'city'
    NUM_TIMESTEPS: 1
    SOLAR_DISTRIBUTION: 'FullExteriorWithReflections'
  building:
    DEFAULT_DATA_STANDARD: ASHRAE # Options: RICS, ASHRAE
  uncertainty:
    DATA_QUALITY_INDICATORS: [reliability, completeness, temporal correlation, geographical correlation, technological representativeness]
    MAX_DQS: 5
    MIN_DQS: 1
  utilities:
    LOG_LEVEL: Error # Options: Fatal, Error, Warn, Info, Debug, Trace

file_paths:
  materials_screening:
    DEFAULT_IMPACT_DATABASE: data/impacts_podlca_data.csv
  transportation:
    CFS_DATA_PATH: data/transportation_cfs_dataset.csv
    CFAF_RAIL_DATA_PATH: data/transportation_cfaf_rail_dataset.csv
    FAF_DATA_PATH: data/transportation_faf_dataset.csv
    FAF_DISTANCE_BANDS: data/transportation_podlca_faf-dist-band.scv
    CFS_STATE_CODE: data/transportation_cfs_state-code.json
    BT_SCTG_CODE: data/transportation_bt_material-sctg.csv
    SCTG_CODE_LIST: data/transportation_cf_sctg-codes.csv
    MARINE_DATA_PATH: data/transportation_podlca_marine.csv
    CFS_MODE_CODE: data/transportation_cfs_mode-codes.json
    FAF_MODE_CODE: data/transportation_faf_mode-codes.json
    ELECTRIC_VEHICLES: data/transportation_podlca_electric-vehicles.csv
    WASTE_TRANSPORT: data/transportation_podlca_waste-transport.csv
    MODE_IMPACTS: data/transportation_podlca_emission.csv
  electricity:
    CAMBIUM_NATIONAL_DATA: data/electricity_cambium_consumption-national.csv
    CAMBIUM_REGIONAL_DATA: data/electricity_cambium_consumption-regional.csv
    CAMBIUM_LOCAL_DATA: data/electricity_cambium_consumption-local.csv
    CAMBIUM_HEADER_MAP: data/electricity_cambium_technology-headers.json
    CAMBIUM_TECHNOLOGY_MAP: data/electricity_cambium_technology-map.json
    CAMBIUM_REGIONS_MAP: data/electricity_cambium_regions-map.json
    ELECTRICITY_IMPACT_NATIONAL_DATA: data/electricity_netl_national-consumption-impacts-by-technology.csv
    ELECTRICITY_IMPACT_REGIONAL_DATA: data/electricity_netl_regional-consumption-impacts-by-technology.csv
    ELECTRICITY_TECHNOLOGIES: data/electricity_netl_electricity-technologies.csv
  eol:
    EOL_DEFAULT_MIXES: data/eol_podlca_default-mixes.csv
    EOL_DEMOLITION_IMPACTS: data/impacts_podlca_eol-demolition-impacts.csv
    EOL_PROCESS_IMPACTS: data/impacts_podlca_eol-process-impacts.csv
  impacts:
    IMPACT_NORMALIZATION_FACTORS: data/impacts_clf_normalization-factors.json
    IMPACT_WEIGHTING_FACTOR_EPA: data/impacts_epa_weighting-factors.json
    IMPACT_WEIGHTING_FACTOR_NIST: data/impacts_nist_weighting-factors.json
  location:
    US_STATES: data/location_faa_us-states.json
    US_STATE_COORDS: data/location_podlca_us-state-coords.csv
    US_STATE_ZIP: data/location_podlca_us-state-zip.csv
    US_ZIP_STATE: data/location_scpike_uszip-state.csv
    FAF_DOMESTIC_REGION: data/transportation_faf_domestic-region.json
    FAF_FOREIGN_REGION: data/transportation_faf_foreign-region.json
    FAF_CITY_REPRESENTATION: data/transportation_podlca_faf-city-representation.json
    US_COAST: data/transportation_podlca_us-coast.json
    FAF_FOREIGN_REGION_COUNTRY: data/transportation_faf_foreign-region-countries.json
    FERC_ZIPCODE_MAP_PATH: data/location_netl_ferc-ba-mapping.csv
    FERC_BA_ZIPCODE_MAP_PATH: data/location_doe_ba-zip-mapping.csv
    GEA_ZIPCODE_MAP_PATH: data/location_cambium_gea-reeds-zip-mapping.csv
    REEDS_BA_ZIPCODE_MAP_PATH: data/location_cambium_gea-reeds-zip-mapping.csv
    CLIMATE_ZONE_ZIPCODE_MAP_PATH: data/location_olsonkundig_climate-zones.csv
  operational:
    CONSTRUCTIONS: data/operational_constructions.idf
    SYSTEMS: data/operational_systems.idf
    TEMP:   ../../temp/pod_lca_operational.idf
    OUTPUT: ../../temp/test_eplus_out
    EPLUS:  ../../temp/EnergyPlus-25-1-0/energyplus
  weather_files:
    1A: data/USA_FL_Miami.Intl.AP.722020_TMY3.epw
    2A: data/USA_FL_Tampa-MacDill.AFB.747880_TMY3.epw
    2B: data/USA_AZ_Tucson-Davis-Monthan.AFB.722745_TMY3.epw
    3A: data/USA_GA_Atlanta-Hartsfield.Jackson.Intl.AP.722190_TMY3.epw
    3B: data/USA_TX_El.Paso.Intl.AP.722700_TMY3.epw
    3C: data/USA_CA_San.Deigo-Brown.Field.Muni.AP.722904_TMY3.epw
    4A: data/USA_NY_New.York-John.F.Kennedy.Intl.AP.744860_TMY3.epw
    4B: data/USA_NM_Albuquerque.Intl.Sunport.723650_TMY3.epw
    4C: data/USA_WA_Seattle-Tacoma.Intl.AP.727930_TMY3.epw
    5A: data/USA_NY_Buffalo.Niagara.Intl.AP.725280_TMY3.epw
    5B: data/USA_CO_Denver-Aurora-Buckley.AFB.724695_TMY3.epw
    5C: data/USA_WA_Port.Angeles-William.R.Fairchild.Intl.AP.727885_TMY3.epw
    6A: data/USA_MN_Rochester.Intl.AP.726440_TMY3.epw
    6B: data/USA_MT_Great.Falls.Intl.AP.727750_TMY3.epw
    7: data/USA_MN_International.Falls.Intl.AP.727470_TMY3.epw
    8: data/USA_AK_Fairbanks.Intl.AP.702610_TMY3.epw
  drf:
    PERTUBATION_LIFETIMES: data/drf_ipcc_pertubation-lifetimes.json
    RADIATIVE_EFFICIENCY: data/drf_ipcc_radiative-efficiency.json
    MOLECULER_WEIGHT: data/drf_none_moleculer-weight.json
    CO2_IRF_PARAMETERS: data/drf_ipcc_co2-irf-parameters.json
    INDIRECT_EFFECTS_FACTORS: data/drf_ipcc_indirect-contributions.json
  building:
    DEFAULT_IMPACT_DATABASE: data/impacts_podlca_building-materials-data.csv
    TEMPLATE_GEOMETRY: data/buildings_podlca_geometry.json
    TEMPLATE_BOM_STRUCTURE: data/buildings_podlca_template-models-structure.csv
    TEMPLATE_BOM_ENCLOSURE_OPAQUE: data/buildings_podlca_template-models-enclosure-opaque.csv
    TEMPLATE_BOM_ENCLOSURE_TRANSLUCENT: data/buildings_podlca_template-models-enclosure-translucent.csv
    TEMPLATE_BOM_ROOFING: data/buildings_podlca_template-models-roofing.csv
    TEMPLATE_MATERIALS_DEFAULT_MAP: data/building_podlca_default-impact-database-entry-mapping.csv
    RICS_SERVICE_LIFE: data/building_rics_service-life.csv
    ASHRAE_SERVICE_LIFE: data/building_ashrae_service-life.csv
    RICS_WASTE_RATE: data/building_rics_waste-rate.csv
    ASHRAE_WASTE_RATE: data/building_ashrae_waste-rate.csv
    DRF_CATEGORIES: data/buildings_podlca_drf-categoris.csv
    EUI: data/building_podlca_eui.csv
    SAMPLE_BUILDING_STRUCTURES: data/buildings_podlca_sample-structures.csv
    IDF_IMPACT_DATA_PRODUCT_MAP: data/building_podlca_idf-to-database-material-mapping.csv
  carbon:
    BIO_MATERIAL_DATA: data\\carbon_podlca_bio-material-data.csv
Keys and Credentials:
  material screening tool: cG9kbGNhbWF0bWFzdGVy

Preferences:
  COLOUR_PALETTES:
    blue: ['#002060', '#00337F', '#4472C4', '#8FAADC', '#D9E2F3']
    orange: ['#7F1C00', '#9C2B00', '#ED7D31', '#F4B183', '#FCE4D6']
    grey: ['#3F3F3F', '#595959', '#A5A5A5', '#D9D9D9', '#F2F2F2']
    yellow: ['#7F6000', '#9F7700', '#FFC000', '#FFD966', '#FFF2CC']
    green: ['#1F4D1F', '#2D6A2D', '#70AD47', '#A9D08E', '#E2EFDA']
    red: ['#7F0000', '#9C0000', '#C00000', '#E26B6B', '#F4CCCC']
    purple: ['#3F1C59', '#5B2A8F', '#7030A0', '#B4A7D6', '#EAD1DC']
  COLOUR_ORDER_LIST: [blue, green, grey, yellow, orange, red, purple]
  COLOUR_BASE: 2   
