ELECTRICITY_TECHNOLOGIES = ["Biomass",
                            "Coal",
                            "Natural gas",
                            "Geothermal",
                            "Hydro",
                            "Mixed",
                            "Nuclear",
                            "Other fossil",
                            "Petroleum",
                            "Other fuels",
                            "Solar",
                            "Solar thermal",
                            "Wind",
                            "SCPC",
                            "SCPC w/ CCS",
                            "SubPC",
                            "SubPC w/ CCS",
                            "NGCC",
                            "NGCC w/ CCS",
                            "OxyPC w/ CCS",
                            "SOFC Coal Conventional Gasifier w/ CCS",
                            "SOFC NG w/ CCS",
                            "SubPC w/ CCS w/ NG Aux"]
